---
project_folder: geoserver_gmf
project_package: geoserver_gmf
application_url: https://localhost:8484/
checker_url: https://172.17.0.1:8484/c2c/health_check?max_level=9
managed_files: []
unmanaged_files: []
template_vars:
  package: geoserver_gmf
  srid: 2056
  extent: 2420000,1030000,2900000,1350000
  authtkt_secret: hah0chah6Bej6chuSuquaiD4aquo3fif1lu4Aetiegaev4uitei4ain0ieXoa1ee
advance: true
env:
  files:
    - env.default
    - env.project
    - env.secrets
  required_args: 0
  help: No arguments needed.
